# Generated by Django 4.2.3 on 2023-10-30 23:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameturn',
            name='turn_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), null=True, size=None),
        ),
        migrations.AddField(
            model_name='scrabblegame',
            name='next_turn_index',
            field=models.IntegerField(default=0),
        ),
    ]
