# Generated by Django 4.2.3 on 2023-12-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0003_alter_gameplayer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameturn',
            name='turn_data',
            field=models.JSONField(null=True),
        ),
    ]
