# Generated by Django 4.2.3 on 2023-12-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0004_gameturn_turn_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrabblegame',
            name='game_type',
            field=models.CharField(choices=[('scrabble', 'Scrabble'), ('upwords', 'Upwords')], default='scrabble', max_length=32),
            preserve_default=False,
        ),
    ]
