# Generated by Django 4.2.3 on 2023-12-10 21:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0005_scrabblegame_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrabblegame',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=5), size=15), size=15),
        ),
    ]
