# Generated by Django 4.2.3 on 2023-12-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0006_alter_scrabblegame_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameturn',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameturn',
            name='turn_action',
            field=models.CharField(choices=[('play', 'Play'), ('exchange', 'Exchange'), ('pass', 'Pass Turn'), ('forfeit', 'Forfeit'), ('end_game', 'End Game')], max_length=32),
        ),
    ]
