# Generated by Django 4.2.3 on 2024-03-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0007_gameturn_deleted_alter_gameturn_turn_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='send_turn_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
