# Generated by Django 4.2.10 on 2024-03-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0009_scrabblegame_use_old_upwords_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrabblegame',
            name='prevent_stack_duplicates',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='scrabblegame',
            name='use_old_upwords_rules',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
