# Generated by Django 4.2.10 on 2024-04-13 19:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0010_scrabblegame_prevent_stack_duplicates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrabblegame',
            name='selected_dictionaries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ospd2', 'OSPD2'), ('ospd3', 'OSPD3'), ('csw12', 'CSW12'), ('ENABLE', 'ENABLE'), ('long', 'Long Words')], max_length=32), null=True, size=None),
        ),
        migrations.AddField(
            model_name='scrabblegame',
            name='validate_words',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
