# Generated by Django 4.2.10 on 2024-06-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0011_scrabblegame_selected_dictionaries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
