# Generated by Django 4.2.3 on 2023-10-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='one_time_passcode',
            field=models.CharField(default='', max_length=32),
        ),
    ]
