# Generated by Django 4.2.21 on 2025-12-18 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_user_one_time_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_email_default',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('new_game', 'New Game'), ('play', 'Play'), ('game_over', 'Game Over')], max_length=32)),
                ('notification_text', models.CharField(max_length=256)),
                ('view_url', models.URLField(max_length=1024)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
